version: '3'

services:
  acme-subscirbers-core-test-postgress:
    image: postgres:16.3
    ports:
      - "10432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testing-subscribers
  acme-subscirbers-importer-core-test-postgress:
    image: postgres:16.3
    ports:
      - "10433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testing-subscribers-importer